-- Seeds the "final form(2).xlsx" price list the business owner provided (Google Sheet,
-- 2026-09-28) - a customer-facing quotation-form template (has Name of
-- Customer/Address/Odometer/Date fields), not a stock-count sheet. It carries
-- SRP prices only, no quantities - every physical product below starts at
-- quantity 0 per branch (per DEC-048, an active zero-stock item stays visible
-- in the catalog rather than being archived) with a flat placeholder
-- reorder_threshold of 3, since the source gives no per-item threshold data.
-- Real quantities need to be entered via Inventory's Receive Stock flow once
-- actually received.
--
-- Category rules applied when parsing the form: an explicit "Carb/FI" split
-- (two prices) became two products, one CARB one FI; a single price on a
-- Carb/FI-labeled item was treated as one interchangeable OTHERS product;
-- the form's own "OTHERS" bearing sub-section and "SERVICES" sub-section
-- were carried through as-is. SERVICES products intentionally get no
-- stock_level row (category = 'SERVICES' is excluded from stock tracking
-- app-wide, see DEC-038).
--
-- Two items were EXCLUDED from this migration, confirmed with the business
-- owner (2026-09-28): 'Axle Bolt front/Rear' has no price anywhere in the
-- source form (skip until priced), and a stray single-price 'Starter Motor
-- Carb/FI' (₱1700) duplicate of the Carb/FI-split entry already seeded below
-- was treated as a form data-entry error and dropped.
--
-- 'Valve Spring Seat' already existed (V15, OEM `12933-12K00-000`, FI,
-- ₱40.00) - this form's ₱80 is treated as an updated real price for the same
-- part (owner confirmed), applied as an UPDATE below rather than a duplicate
-- INSERT; its category/OEM number are left untouched.
UPDATE product SET unit_price = 80.00, updated_at = now() WHERE name = 'Valve Spring Seat';

INSERT INTO product (name, brand_tag, category, unit_price, is_active, created_at, updated_at) VALUES
    ('Balancer Dumper (2pcs)', 'SGP', 'OTHERS', 490.00, true, now(), now()),
    ('Spacer Mags Rear', 'SGP', 'OTHERS', 220.00, true, now(), now()),
    ('Spacer Mags Front', 'SGP', 'OTHERS', 180.00, true, now(), now()),
    ('Sprocket Set SSS Gold', 'SSS', 'OTHERS', 2400.00, true, now(), now()),
    ('Sprocket Set SSS Gold Installation', 'SSS', 'SERVICES', 350.00, true, now(), now()),
    ('Sprocket Set SSS Silver', 'SSS', 'OTHERS', 2000.00, true, now(), now()),
    ('Sprocket Set SSS Silver Installation', 'SSS', 'SERVICES', 350.00, true, now(), now()),
    ('Ignition Coil Protector (Carb)', 'SGP', 'CARB', 2350.00, true, now(), now()),
    ('Ignition Coil Protector (FI)', 'SGP', 'FI', 2550.00, true, now(), now()),
    ('MDL Package - Basic', 'MDL', 'OTHERS', 1700.00, true, now(), now()),
    ('MDL Package - Senlo T1/M1A 60W', 'Senlo', 'OTHERS', 3800.00, true, now(), now()),
    ('MDL Package - Senlo M5 100W', 'Senlo', 'OTHERS', 5450.00, true, now(), now()),
    ('Refresh (Carb)', NULL, 'SERVICES', 3050.00, true, now(), now()),
    ('Refresh (FI)', NULL, 'SERVICES', 4500.00, true, now(), now()),
    ('Clutch Side Labor (Carb)', NULL, 'SERVICES', 400.00, true, now(), now()),
    ('Clutch Side Labor (FI)', NULL, 'SERVICES', 650.00, true, now(), now()),
    ('Front Shock Tune', NULL, 'SERVICES', 1500.00, true, now(), now()),
    ('Rear Shock Tune', NULL, 'SERVICES', 1800.00, true, now(), now()),
    ('Rethread 6mm', NULL, 'SERVICES', 150.00, true, now(), now()),
    ('Rethread 7mm', NULL, 'SERVICES', 200.00, true, now(), now()),
    ('Rethread 8mm', NULL, 'SERVICES', 350.00, true, now(), now()),
    ('Mutarru Radiator (FI)', 'Mutarru', 'FI', 3600.00, true, now(), now()),
    ('Race Power Radiator (FI)', 'Race Power', 'FI', 3600.00, true, now(), now()),
    ('Top Cover Bolt', 'SGP', 'OTHERS', 80.00, true, now(), now()),
    ('Balancer Gear Counter (Carb)', 'SGP', 'CARB', 950.00, true, now(), now()),
    ('Balancer Gear Counter (FI)', 'SGP', 'FI', 1220.00, true, now(), now()),
    ('Air Filter (Carb)', 'SGP', 'CARB', 410.00, true, now(), now()),
    ('Air Filter (FI)', 'SGP', 'FI', 470.00, true, now(), now()),
    ('Balancer Crank', 'SGP', 'OTHERS', 2300.00, true, now(), now()),
    ('Balancer Gear Carb/FI', 'SGP', 'OTHERS', 1300.00, true, now(), now()),
    ('Balancer Inner Race', 'SGP', 'OTHERS', 720.00, true, now(), now()),
    ('Balancer Pin', 'SGP', 'OTHERS', 130.00, true, now(), now()),
    ('Balancer Spring', 'SGP', 'OTHERS', 180.00, true, now(), now()),
    ('Ball Race Carb/FI', 'SGP', 'OTHERS', 1620.00, true, now(), now()),
    ('Base Gasket (Carb)', 'SGP', 'CARB', 100.00, true, now(), now()),
    ('Base Gasket (FI)', 'SGP', 'FI', 190.00, true, now(), now()),
    ('Body Switch (Carb)', 'SGP', 'CARB', 450.00, true, now(), now()),
    ('Body Switch (FI)', 'SGP', 'FI', 1880.00, true, now(), now()),
    ('Break Pad Front (Carb)', 'SGP', 'CARB', 700.00, true, now(), now()),
    ('Break Pad Front (FI)', 'SGP', 'FI', 830.00, true, now(), now()),
    ('Break Pad Rear (Carb)', 'SGP', 'CARB', 620.00, true, now(), now()),
    ('Break Pad Rear (FI)', 'SGP', 'FI', 1590.00, true, now(), now()),
    ('Chain Guide Long Carb/FI', 'SGP', 'OTHERS', 450.00, true, now(), now()),
    ('Chain Guide Short Carb/FI', 'SGP', 'OTHERS', 480.00, true, now(), now()),
    ('Clutch Arm', 'SGP', 'OTHERS', 510.00, true, now(), now()),
    ('Clutch Holder', 'SGP', 'OTHERS', 850.00, true, now(), now()),
    ('Clutch Cable (Carb)', 'SGP', 'CARB', 880.00, true, now(), now()),
    ('Clutch Cable (FI)', 'SGP', 'FI', 500.00, true, now(), now()),
    ('Clutch Housing (Carb)', 'SGP', 'CARB', 5030.00, true, now(), now()),
    ('Clutch Housing (FI)', 'SGP', 'FI', 5440.00, true, now(), now()),
    ('Clutch Hub (Carb)', 'SGP', 'CARB', 490.00, true, now(), now()),
    ('Clutch Hub (FI)', 'SGP', 'FI', 600.00, true, now(), now()),
    ('Clutch Linning Carb/FI', 'SGP', 'OTHERS', 1660.00, true, now(), now()),
    ('Clutch Plate', 'SGP', 'OTHERS', 125.00, true, now(), now()),
    ('Clutch Release Bearing', 'SGP', 'OTHERS', 420.00, true, now(), now()),
    ('Clutch Side Gasket Carb/FI', 'SGP', 'OTHERS', 220.00, true, now(), now()),
    ('Connecting Rod Kit Carb/FI', 'SGP', 'OTHERS', 3250.00, true, now(), now()),
    ('Crankshaft Bearing Clutchside', 'SGP', 'OTHERS', 1100.00, true, now(), now()),
    ('Crankshaft Bearing Magneto', 'SGP', 'OTHERS', 1100.00, true, now(), now()),
    ('Drain Plug Bolts', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Dust Seal Front Shock', 'SGP', 'OTHERS', 160.00, true, now(), now()),
    ('Exhaust Cams Carb/FI', 'SGP', 'OTHERS', 6970.00, true, now(), now()),
    ('Exhaust Valve (Carb)', 'SGP', 'CARB', 470.00, true, now(), now()),
    ('Exhaust Valve (FI)', 'SGP', 'FI', 450.00, true, now(), now()),
    ('Fan Relay', 'SGP', 'OTHERS', 330.00, true, now(), now()),
    ('Front Shock Ring Stopper', 'SGP', 'OTHERS', 60.00, true, now(), now()),
    ('Fuel Filter (Carb)', 'SGP', 'CARB', 30.00, true, now(), now()),
    ('Fuel Filter (FI)', 'SGP', 'FI', 380.00, true, now(), now()),
    ('Fuel Hose RFI', 'SGP', 'FI', 860.00, true, now(), now()),
    ('Fuel Pump RFI', 'SGP', 'FI', 4320.00, true, now(), now()),
    ('Gasket Muffler', 'SGP', 'OTHERS', 250.00, true, now(), now()),
    ('Head Gasket FI', 'SGP', 'FI', 360.00, true, now(), now()),
    ('High Tension Seal', 'SGP', 'OTHERS', 170.00, true, now(), now()),
    ('Idle Screw FI', 'SGP', 'FI', 150.00, true, now(), now()),
    ('Ignition Switch Carb', 'SGP', 'CARB', 1650.00, true, now(), now()),
    ('Ignition Switch FI', 'SGP', 'FI', 1910.00, true, now(), now()),
    ('Injector SGP', 'SGP', 'OTHERS', 1500.00, true, now(), now()),
    ('Insulator Intake Pipe', 'SGP', 'OTHERS', 350.00, true, now(), now()),
    ('Intake Cams Carb/FI', 'SGP', 'OTHERS', 3700.00, true, now(), now()),
    ('Intake Valve (Carb)', 'SGP', 'CARB', 320.00, true, now(), now()),
    ('Intake Valve (FI)', 'SGP', 'FI', 410.00, true, now(), now()),
    ('Kunya Magneto', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Lens Oil Inspection', 'SGP', 'OTHERS', 600.00, true, now(), now()),
    ('Lever Break', 'SGP', 'OTHERS', 350.00, true, now(), now()),
    ('Lever Clutch', 'SGP', 'OTHERS', 350.00, true, now(), now()),
    ('Magento Gasket Carb/FI', 'SGP', 'OTHERS', 200.00, true, now(), now()),
    ('Manifold', 'SGP', 'OTHERS', 950.00, true, now(), now()),
    ('O Ring Insulator', 'SGP', 'OTHERS', 200.00, true, now(), now()),
    ('O Ring Neutral Sensor', 'SGP', 'OTHERS', 100.00, true, now(), now()),
    ('O Ring Oil Filter Cap', 'SGP', 'OTHERS', 60.00, true, now(), now()),
    ('O Ring Oil Filter Small', 'SGP', 'OTHERS', 40.00, true, now(), now()),
    ('Oil 1L', 'SGP', 'OTHERS', 420.00, true, now(), now()),
    ('Oil Cap', 'SGP', 'OTHERS', 220.00, true, now(), now()),
    ('Oil Filter', 'SGP', 'OTHERS', 130.00, true, now(), now()),
    ('Oil Filter Screen', 'SGP', 'OTHERS', 250.00, true, now(), now()),
    ('Oil Pump (Carb)', 'SGP', 'CARB', 860.00, true, now(), now()),
    ('Oil Pump (FI)', 'SGP', 'FI', 500.00, true, now(), now()),
    ('Oil Pump Gear Carb/FI', 'SGP', 'OTHERS', 240.00, true, now(), now()),
    ('Oil Seal Clutch', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Oil Seal Driveshaft Carb/FI', 'SGP', 'OTHERS', 300.00, true, now(), now()),
    ('Oil Seal Front Shock', 'SGP', 'OTHERS', 250.00, true, now(), now()),
    ('Oil Seal Kambyo', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Oil Seal Kick', 'SGP', 'OTHERS', 80.00, true, now(), now()),
    ('Oil Seal Rear Shock', 'SGP', 'OTHERS', 650.00, true, now(), now()),
    ('Oil Seal Small', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Oil Seal Water Pump Case FI', 'SGP', 'FI', 200.00, true, now(), now()),
    ('Pin Dowel Block', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Pin Dowel Block Head', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Piston  Carb/FI', 'SGP', 'OTHERS', 910.00, true, now(), now()),
    ('Piston Pin', 'SGP', 'OTHERS', 350.00, true, now(), now()),
    ('Piston Ring Carb/FI', 'SGP', 'OTHERS', 970.00, true, now(), now()),
    ('Pressure Plate (Carb)', 'SGP', 'CARB', 770.00, true, now(), now()),
    ('Pressure Plate (FI)', 'SGP', 'FI', 920.00, true, now(), now()),
    ('Rack Release', 'SGP', 'OTHERS', 360.00, true, now(), now()),
    ('Return Spring', 'SGP', 'OTHERS', 180.00, true, now(), now()),
    ('Rotor Disk Front', 'SGP', 'OTHERS', 2940.00, true, now(), now()),
    ('Rotor Disk Rear', 'SGP', 'OTHERS', 2740.00, true, now(), now()),
    ('Rubber Dumper', 'SGP', 'OTHERS', 390.00, true, now(), now()),
    ('Shim Cap', 'SGP', 'OTHERS', 450.00, true, now(), now()),
    ('Side Mirror Reborn set', 'SGP', 'OTHERS', 1820.00, true, now(), now()),
    ('Spacer Axle Front/Rear', 'SGP', 'OTHERS', 300.00, true, now(), now()),
    ('Spacer Bearing  Mags', 'SGP', 'OTHERS', 170.00, true, now(), now()),
    ('Sparkplug Cap Assy', 'SGP', 'OTHERS', 650.00, true, now(), now()),
    ('Sprocket Hub', 'SGP', 'OTHERS', 820.00, true, now(), now()),
    ('Sprocket Hub Spacer', 'SGP', 'OTHERS', 300.00, true, now(), now()),
    ('Starter Motor', 'SGP', 'OTHERS', 2500.00, true, now(), now()),
    ('Starter Motor (Carb)', 'SGP', 'CARB', 1560.00, true, now(), now()),
    ('Starter Motor (FI)', 'SGP', 'FI', 1650.00, true, now(), now()),
    ('Starter Relay', 'SGP', 'OTHERS', 860.00, true, now(), now()),
    ('Tensionare Carb/FI', 'SGP', 'OTHERS', 1470.00, true, now(), now()),
    ('Tensioner Gasket', 'SGP', 'OTHERS', 30.00, true, now(), now()),
    ('Throttle Cable FI stock', 'SGP', 'FI', 440.00, true, now(), now()),
    ('Timming Chain Carb/FI', 'SGP', 'OTHERS', 1050.00, true, now(), now()),
    ('Top Cover Gasket', 'SGP', 'OTHERS', 650.00, true, now(), now()),
    ('Valve Lock', 'SGP', 'OTHERS', 170.00, true, now(), now()),
    ('Valve Retainer', 'SGP', 'OTHERS', 170.00, true, now(), now()),
    ('Valve Seal', 'SGP', 'OTHERS', 130.00, true, now(), now()),
    ('Valve Spring', 'SGP', 'OTHERS', 200.00, true, now(), now()),
    ('Vendix Drive Carb/FI', 'SGP', 'OTHERS', 4050.00, true, now(), now()),
    ('Washer Block', 'SGP', 'OTHERS', 250.00, true, now(), now()),
    ('Washer Clutch Hub', 'SGP', 'OTHERS', 350.00, true, now(), now()),
    ('Water Pump Oil Seal', 'SGP', 'OTHERS', 690.00, true, now(), now()),
    ('Water Pump Shaft', 'SGP', 'OTHERS', 410.00, true, now(), now()),
    ('Water Temperature Sensor', 'SGP', 'OTHERS', 2800.00, true, now(), now()),
    ('Wave Washer (Carb)', 'SGP', 'CARB', 350.00, true, now(), now()),
    ('Wave Washer (FI)', 'SGP', 'FI', 220.00, true, now(), now()),
    ('Bearing 6002', 'Bearing', 'OTHERS', 180.00, true, now(), now()),
    ('Bearing 6004', 'Bearing', 'OTHERS', 250.00, true, now(), now()),
    ('Bearing 6200', 'Bearing', 'OTHERS', 250.00, true, now(), now()),
    ('Bearing 6201', 'Bearing', 'OTHERS', 160.00, true, now(), now()),
    ('Bearing 6202', 'Bearing', 'OTHERS', 170.00, true, now(), now()),
    ('Bearing 6203', 'Bearing', 'OTHERS', 180.00, true, now(), now()),
    ('Bearing 6204', 'Bearing', 'OTHERS', 250.00, true, now(), now()),
    ('Bearing 6301', 'Bearing', 'OTHERS', 170.00, true, now(), now()),
    ('Aircut', 'SGP', 'OTHERS', 550.00, true, now(), now()),
    ('Block 62mm steel Carb/FI', 'SGP', 'OTHERS', 3500.00, true, now(), now()),
    ('Block 62mm Steel FI', 'SGP', 'FI', 4500.00, true, now(), now()),
    ('Block 68mm Chrome Bore FI', 'SGP', 'FI', 6900.00, true, now(), now()),
    ('Block 68mm Steel Carb', 'SGP', 'CARB', 3800.00, true, now(), now()),
    ('Break Hose Front', 'SGP', 'OTHERS', 850.00, true, now(), now()),
    ('Break Hose Rear', 'SGP', 'OTHERS', 650.00, true, now(), now()),
    ('Breather Filter set FI', 'SGP', 'FI', 750.00, true, now(), now()),
    ('Carbon Brush (Carb)', 'SGP', 'CARB', 350.00, true, now(), now()),
    ('Carbon Brush (FI)', 'SGP', 'FI', 660.00, true, now(), now()),
    ('Carburetor Cleaner', 'SGP', 'OTHERS', 170.00, true, now(), now()),
    ('Clutch Spring set', 'SGP', 'OTHERS', 1000.00, true, now(), now()),
    ('Coolant', 'SGP', 'OTHERS', 380.00, true, now(), now()),
    ('Domino Switch', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Elbow (Carb)', 'SGP', 'CARB', 1200.00, true, now(), now()),
    ('Elbow (FI)', 'SGP', 'FI', 1550.00, true, now(), now()),
    ('Exos Pipe Set (Carb)', 'SGP', 'CARB', 3350.00, true, now(), now()),
    ('Exos Pipe Set (FI)', 'SGP', 'FI', 3550.00, true, now(), now()),
    ('Exhaust Gasket', 'SGP', 'OTHERS', 30.00, true, now(), now()),
    ('Faito Connecting Rod Kit with Bearing', 'SGP', 'OTHERS', 4250.00, true, now(), now()),
    ('Fork Oil', 'SGP', 'OTHERS', 290.00, true, now(), now()),
    ('Handle Grip', 'SGP', 'OTHERS', 200.00, true, now(), now()),
    ('Hydrolic Switch', 'SGP', 'OTHERS', 350.00, true, now(), now()),
    ('Inner Tube', 'SGP', 'OTHERS', 3450.00, true, now(), now()),
    ('Jettings', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('Koso Evo 30mm', 'SGP', 'OTHERS', 6250.00, true, now(), now()),
    ('Koso Evo 32mm', 'SGP', 'OTHERS', 6450.00, true, now(), now()),
    ('LED Light', 'SGP', 'OTHERS', 750.00, true, now(), now()),
    ('Pito sa Gulong', 'SGP', 'OTHERS', 100.00, true, now(), now()),
    ('Pitsbike 34mm TB', 'SGP', 'OTHERS', 3400.00, true, now(), now()),
    ('Pitsbike Crankshaft Bearing', 'SGP', 'OTHERS', 1800.00, true, now(), now()),
    ('Pitsbike Oil Pump', 'SGP', 'OTHERS', 1700.00, true, now(), now()),
    ('Pitsbike Racing ECU', 'SGP', 'OTHERS', 6500.00, true, now(), now()),
    ('Pitsbike Tech 2 CDI', 'SGP', 'OTHERS', 5500.00, true, now(), now()),
    ('Pitsbike TPS', 'SGP', 'OTHERS', 1700.00, true, now(), now()),
    ('Race Power Monoshock4800', 'SGP', 'OTHERS', 5500.00, true, now(), now()),
    ('Bom X Monoshock', 'SGP', 'OTHERS', 7500.00, true, now(), now()),
    ('Bom  X Single Shifter', 'SGP', 'OTHERS', 5500.00, true, now(), now()),
    ('Shims', 'SGP', 'OTHERS', 250.00, true, now(), now()),
    ('Sparkplug Brisk Blue', 'SGP', 'OTHERS', 600.00, true, now(), now()),
    ('Sparkplug Gpower', 'SGP', 'OTHERS', 320.00, true, now(), now()),
    ('Sparkplug Racing Red', 'SGP', 'OTHERS', 900.00, true, now(), now()),
    ('sgp oil strainer', 'SGP', 'OTHERS', 300.00, true, now(), now()),
    ('Stud Bolt', 'SGP', 'OTHERS', 80.00, true, now(), now()),
    ('Throttle Cable Shogun', 'SGP', 'OTHERS', 150.00, true, now(), now()),
    ('UMA Quick Throttle', 'SGP', 'OTHERS', 1200.00, true, now(), now()),
    ('Velocity Throttle Body FI', 'SGP', 'FI', 350.00, true, now(), now()),
    ('Voltmeter', 'SGP', 'OTHERS', 250.00, true, now(), now()),
    ('Yolac Cams', 'SGP', 'OTHERS', 5000.00, true, now(), now()),
    ('8 Rows oil Cooler Carb with Installation', 'SGP', 'CARB', 3500.00, true, now(), now()),
    ('RCB Front Caliper', 'SGP', 'OTHERS', 3300.00, true, now(), now()),
    ('RCB Rear Caliper', 'SGP', 'OTHERS', 3600.00, true, now(), now()),
    ('Bom X Handle Grip', 'SGP', 'OTHERS', 250.00, true, now(), now()),
    ('RCB/JRP Handle Grip', 'SGP', 'OTHERS', 200.00, true, now(), now()),
    ('Quantum Battery', 'SGP', 'OTHERS', 1550.00, true, now(), now()),
    ('PCC SET', NULL, 'SERVICES', 13000.00, true, now(), now()),
    ('180cc with 28mm Carb', NULL, 'SERVICES', 9450.00, true, now(), now()),
    ('180cc FI', NULL, 'SERVICES', 21200.00, true, now(), now()),
    ('Basic Set (ECU/TB/Dyno Tune)', NULL, 'SERVICES', 15600.00, true, now(), now()),
    ('PortHicom', NULL, 'SERVICES', 6000.00, true, now(), now()),
    ('REMAP w/ Wide Band Nut', NULL, 'SERVICES', 3500.00, true, now(), now()),
    ('Superstock', NULL, 'SERVICES', 17200.00, true, now(), now()),
    ('PMS 1', NULL, 'SERVICES', 1470.00, true, now(), now()),
    ('PMS 2', NULL, 'SERVICES', 2740.00, true, now(), now()),
    ('PMS 3', NULL, 'SERVICES', 5610.00, true, now(), now()),
    ('TB cleaning', NULL, 'SERVICES', 450.00, true, now(), now()),
    ('Carb / Install', NULL, 'SERVICES', 2200.00, true, now(), now()),
    ('Carb Cleaning', NULL, 'SERVICES', 450.00, true, now(), now()),
    ('Chain adjust', NULL, 'SERVICES', 50.00, true, now(), now()),
    ('Clearance/Shims', NULL, 'SERVICES', 1500.00, true, now(), now()),
    ('Clutch Housing Repair', NULL, 'SERVICES', 350.00, true, now(), now()),
    ('Magneto Side Labor', NULL, 'SERVICES', 400.00, true, now(), now()),
    ('Full Wave', NULL, 'SERVICES', 1500.00, true, now(), now()),
    ('Head Repair', NULL, 'SERVICES', 350.00, true, now(), now()),
    ('PIAA Package', NULL, 'SERVICES', 1700.00, true, now(), now()),
    ('Reset Tensionare', NULL, 'SERVICES', 250.00, true, now(), now());

-- Initialize zero stock at both branches for every physical (non-SERVICES)
-- product just inserted above.
INSERT INTO stock_level (product_id, branch_id, quantity, reorder_threshold, updated_at)
SELECT p.id, b.id, 0, 3, now()
FROM product p
CROSS JOIN branch b
WHERE b.code IN ('MAIN', 'MASINAG')
  AND p.category <> 'SERVICES'
  AND p.name IN (
    'Balancer Dumper (2pcs)',
    'Spacer Mags Rear',
    'Spacer Mags Front',
    'Sprocket Set SSS Gold',
    'Sprocket Set SSS Silver',
    'Ignition Coil Protector (Carb)',
    'Ignition Coil Protector (FI)',
    'MDL Package - Basic',
    'MDL Package - Senlo T1/M1A 60W',
    'MDL Package - Senlo M5 100W',
    'Mutarru Radiator (FI)',
    'Race Power Radiator (FI)',
    'Top Cover Bolt',
    'Balancer Gear Counter (Carb)',
    'Balancer Gear Counter (FI)',
    'Air Filter (Carb)',
    'Air Filter (FI)',
    'Balancer Crank',
    'Balancer Gear Carb/FI',
    'Balancer Inner Race',
    'Balancer Pin',
    'Balancer Spring',
    'Ball Race Carb/FI',
    'Base Gasket (Carb)',
    'Base Gasket (FI)',
    'Body Switch (Carb)',
    'Body Switch (FI)',
    'Break Pad Front (Carb)',
    'Break Pad Front (FI)',
    'Break Pad Rear (Carb)',
    'Break Pad Rear (FI)',
    'Chain Guide Long Carb/FI',
    'Chain Guide Short Carb/FI',
    'Clutch Arm',
    'Clutch Holder',
    'Clutch Cable (Carb)',
    'Clutch Cable (FI)',
    'Clutch Housing (Carb)',
    'Clutch Housing (FI)',
    'Clutch Hub (Carb)',
    'Clutch Hub (FI)',
    'Clutch Linning Carb/FI',
    'Clutch Plate',
    'Clutch Release Bearing',
    'Clutch Side Gasket Carb/FI',
    'Connecting Rod Kit Carb/FI',
    'Crankshaft Bearing Clutchside',
    'Crankshaft Bearing Magneto',
    'Drain Plug Bolts',
    'Dust Seal Front Shock',
    'Exhaust Cams Carb/FI',
    'Exhaust Valve (Carb)',
    'Exhaust Valve (FI)',
    'Fan Relay',
    'Front Shock Ring Stopper',
    'Fuel Filter (Carb)',
    'Fuel Filter (FI)',
    'Fuel Hose RFI',
    'Fuel Pump RFI',
    'Gasket Muffler',
    'Head Gasket FI',
    'High Tension Seal',
    'Idle Screw FI',
    'Ignition Switch Carb',
    'Ignition Switch FI',
    'Injector SGP',
    'Insulator Intake Pipe',
    'Intake Cams Carb/FI',
    'Intake Valve (Carb)',
    'Intake Valve (FI)',
    'Kunya Magneto',
    'Lens Oil Inspection',
    'Lever Break',
    'Lever Clutch',
    'Magento Gasket Carb/FI',
    'Manifold',
    'O Ring Insulator',
    'O Ring Neutral Sensor',
    'O Ring Oil Filter Cap',
    'O Ring Oil Filter Small',
    'Oil 1L',
    'Oil Cap',
    'Oil Filter',
    'Oil Filter Screen',
    'Oil Pump (Carb)',
    'Oil Pump (FI)',
    'Oil Pump Gear Carb/FI',
    'Oil Seal Clutch',
    'Oil Seal Driveshaft Carb/FI',
    'Oil Seal Front Shock',
    'Oil Seal Kambyo',
    'Oil Seal Kick',
    'Oil Seal Rear Shock',
    'Oil Seal Small',
    'Oil Seal Water Pump Case FI',
    'Pin Dowel Block',
    'Pin Dowel Block Head',
    'Piston  Carb/FI',
    'Piston Pin',
    'Piston Ring Carb/FI',
    'Pressure Plate (Carb)',
    'Pressure Plate (FI)',
    'Rack Release',
    'Return Spring',
    'Rotor Disk Front',
    'Rotor Disk Rear',
    'Rubber Dumper',
    'Shim Cap',
    'Side Mirror Reborn set',
    'Spacer Axle Front/Rear',
    'Spacer Bearing  Mags',
    'Sparkplug Cap Assy',
    'Sprocket Hub',
    'Sprocket Hub Spacer',
    'Starter Motor',
    'Starter Motor (Carb)',
    'Starter Motor (FI)',
    'Starter Relay',
    'Tensionare Carb/FI',
    'Tensioner Gasket',
    'Throttle Cable FI stock',
    'Timming Chain Carb/FI',
    'Top Cover Gasket',
    'Valve Lock',
    'Valve Retainer',
    'Valve Seal',
    'Valve Spring',
    'Vendix Drive Carb/FI',
    'Washer Block',
    'Washer Clutch Hub',
    'Water Pump Oil Seal',
    'Water Pump Shaft',
    'Water Temperature Sensor',
    'Wave Washer (Carb)',
    'Wave Washer (FI)',
    'Bearing 6002',
    'Bearing 6004',
    'Bearing 6200',
    'Bearing 6201',
    'Bearing 6202',
    'Bearing 6203',
    'Bearing 6204',
    'Bearing 6301',
    'Aircut',
    'Block 62mm steel Carb/FI',
    'Block 62mm Steel FI',
    'Block 68mm Chrome Bore FI',
    'Block 68mm Steel Carb',
    'Break Hose Front',
    'Break Hose Rear',
    'Breather Filter set FI',
    'Carbon Brush (Carb)',
    'Carbon Brush (FI)',
    'Carburetor Cleaner',
    'Clutch Spring set',
    'Coolant',
    'Domino Switch',
    'Elbow (Carb)',
    'Elbow (FI)',
    'Exos Pipe Set (Carb)',
    'Exos Pipe Set (FI)',
    'Exhaust Gasket',
    'Faito Connecting Rod Kit with Bearing',
    'Fork Oil',
    'Handle Grip',
    'Hydrolic Switch',
    'Inner Tube',
    'Jettings',
    'Koso Evo 30mm',
    'Koso Evo 32mm',
    'LED Light',
    'Pito sa Gulong',
    'Pitsbike 34mm TB',
    'Pitsbike Crankshaft Bearing',
    'Pitsbike Oil Pump',
    'Pitsbike Racing ECU',
    'Pitsbike Tech 2 CDI',
    'Pitsbike TPS',
    'Race Power Monoshock4800',
    'Bom X Monoshock',
    'Bom  X Single Shifter',
    'Shims',
    'Sparkplug Brisk Blue',
    'Sparkplug Gpower',
    'Sparkplug Racing Red',
    'sgp oil strainer',
    'Stud Bolt',
    'Throttle Cable Shogun',
    'UMA Quick Throttle',
    'Velocity Throttle Body FI',
    'Voltmeter',
    'Yolac Cams',
    '8 Rows oil Cooler Carb with Installation',
    'RCB Front Caliper',
    'RCB Rear Caliper',
    'Bom X Handle Grip',
    'RCB/JRP Handle Grip',
    'Quantum Battery'
  );
