-- Removes every product NOT in the business owner's final catalog
-- ('final form(2).xlsx', seeded via V22) - explicit owner instruction
-- (2026-09-28): the 159 pre-existing products (Raider R150 FI research
-- catalog, bearings, misc seeded/test items from earlier sessions) are no
-- longer the real product line and are being fully removed, not archived.
--
-- Since the V22 catalog was only seeded today with zero stock, none of it
-- has ever been sold or received - confirmed via a live query that zero
-- sales/receiving records mix an old product with a V22 product. That means
-- every sale and stock_in row in this database exclusively references a
-- product being removed here, so this migration deletes them outright
-- (rather than leaving orphaned, line-item-less parent rows behind) instead
-- of just unlinking them.
--
-- THIS IS A DESTRUCTIVE, IRREVERSIBLE DATA MIGRATION - it will also delete
-- every previously-recorded sale and stock-receiving record. A full pg_dump
-- backup of the pre-cleanup database was taken locally before this ran
-- (2026-09-28, not committed to the repo - see chat/session record).
--
-- The KEEP_NAMES list below is exactly the 230 products seeded by V22 plus
-- 'Valve Spring Seat' (pre-existing, price-updated by V22 rather than
-- re-inserted since it was already in the catalog under the same name).

DELETE FROM sale_line
WHERE product_id IN (SELECT id FROM product WHERE name NOT IN (
    'Balancer Dumper (2pcs)',
    'Spacer Mags Rear',
    'Spacer Mags Front',
    'Sprocket Set SSS Gold',
    'Sprocket Set SSS Gold Installation',
    'Sprocket Set SSS Silver',
    'Sprocket Set SSS Silver Installation',
    'Ignition Coil Protector (Carb)',
    'Ignition Coil Protector (FI)',
    'MDL Package - Basic',
    'MDL Package - Senlo T1/M1A 60W',
    'MDL Package - Senlo M5 100W',
    'Refresh (Carb)',
    'Refresh (FI)',
    'Clutch Side Labor (Carb)',
    'Clutch Side Labor (FI)',
    'Front Shock Tune',
    'Rear Shock Tune',
    'Rethread 6mm',
    'Rethread 7mm',
    'Rethread 8mm',
    'Mutarru Radiator (FI)',
    'Race Power Radiator (FI)',
    'Top Cover Bolt',
    'Balancer Gear Counter (Carb)',
    'Balancer Gear Counter (FI)',
    'Air Filter (Carb)',
    'Air Filter (FI)',
    'Balancer Crank',
    'Balancer Gear Carb/FI',
    'Balancer Inner Race',
    'Balancer Pin',
    'Balancer Spring',
    'Ball Race Carb/FI',
    'Base Gasket (Carb)',
    'Base Gasket (FI)',
    'Body Switch (Carb)',
    'Body Switch (FI)',
    'Break Pad Front (Carb)',
    'Break Pad Front (FI)',
    'Break Pad Rear (Carb)',
    'Break Pad Rear (FI)',
    'Chain Guide Long Carb/FI',
    'Chain Guide Short Carb/FI',
    'Clutch Arm',
    'Clutch Holder',
    'Clutch Cable (Carb)',
    'Clutch Cable (FI)',
    'Clutch Housing (Carb)',
    'Clutch Housing (FI)',
    'Clutch Hub (Carb)',
    'Clutch Hub (FI)',
    'Clutch Linning Carb/FI',
    'Clutch Plate',
    'Clutch Release Bearing',
    'Clutch Side Gasket Carb/FI',
    'Connecting Rod Kit Carb/FI',
    'Crankshaft Bearing Clutchside',
    'Crankshaft Bearing Magneto',
    'Drain Plug Bolts',
    'Dust Seal Front Shock',
    'Exhaust Cams Carb/FI',
    'Exhaust Valve (Carb)',
    'Exhaust Valve (FI)',
    'Fan Relay',
    'Front Shock Ring Stopper',
    'Fuel Filter (Carb)',
    'Fuel Filter (FI)',
    'Fuel Hose RFI',
    'Fuel Pump RFI',
    'Gasket Muffler',
    'Head Gasket FI',
    'High Tension Seal',
    'Idle Screw FI',
    'Ignition Switch Carb',
    'Ignition Switch FI',
    'Injector SGP',
    'Insulator Intake Pipe',
    'Intake Cams Carb/FI',
    'Intake Valve (Carb)',
    'Intake Valve (FI)',
    'Kunya Magneto',
    'Lens Oil Inspection',
    'Lever Break',
    'Lever Clutch',
    'Magento Gasket Carb/FI',
    'Manifold',
    'O Ring Insulator',
    'O Ring Neutral Sensor',
    'O Ring Oil Filter Cap',
    'O Ring Oil Filter Small',
    'Oil 1L',
    'Oil Cap',
    'Oil Filter',
    'Oil Filter Screen',
    'Oil Pump (Carb)',
    'Oil Pump (FI)',
    'Oil Pump Gear Carb/FI',
    'Oil Seal Clutch',
    'Oil Seal Driveshaft Carb/FI',
    'Oil Seal Front Shock',
    'Oil Seal Kambyo',
    'Oil Seal Kick',
    'Oil Seal Rear Shock',
    'Oil Seal Small',
    'Oil Seal Water Pump Case FI',
    'Pin Dowel Block',
    'Pin Dowel Block Head',
    'Piston  Carb/FI',
    'Piston Pin',
    'Piston Ring Carb/FI',
    'Pressure Plate (Carb)',
    'Pressure Plate (FI)',
    'Rack Release',
    'Return Spring',
    'Rotor Disk Front',
    'Rotor Disk Rear',
    'Rubber Dumper',
    'Shim Cap',
    'Side Mirror Reborn set',
    'Spacer Axle Front/Rear',
    'Spacer Bearing  Mags',
    'Sparkplug Cap Assy',
    'Sprocket Hub',
    'Sprocket Hub Spacer',
    'Starter Motor',
    'Starter Motor (Carb)',
    'Starter Motor (FI)',
    'Starter Relay',
    'Tensionare Carb/FI',
    'Tensioner Gasket',
    'Throttle Cable FI stock',
    'Timming Chain Carb/FI',
    'Top Cover Gasket',
    'Valve Lock',
    'Valve Retainer',
    'Valve Seal',
    'Valve Spring',
    'Vendix Drive Carb/FI',
    'Washer Block',
    'Washer Clutch Hub',
    'Water Pump Oil Seal',
    'Water Pump Shaft',
    'Water Temperature Sensor',
    'Wave Washer (Carb)',
    'Wave Washer (FI)',
    'Bearing 6002',
    'Bearing 6004',
    'Bearing 6200',
    'Bearing 6201',
    'Bearing 6202',
    'Bearing 6203',
    'Bearing 6204',
    'Bearing 6301',
    'Aircut',
    'Block 62mm steel Carb/FI',
    'Block 62mm Steel FI',
    'Block 68mm Chrome Bore FI',
    'Block 68mm Steel Carb',
    'Break Hose Front',
    'Break Hose Rear',
    'Breather Filter set FI',
    'Carbon Brush (Carb)',
    'Carbon Brush (FI)',
    'Carburetor Cleaner',
    'Clutch Spring set',
    'Coolant',
    'Domino Switch',
    'Elbow (Carb)',
    'Elbow (FI)',
    'Exos Pipe Set (Carb)',
    'Exos Pipe Set (FI)',
    'Exhaust Gasket',
    'Faito Connecting Rod Kit with Bearing',
    'Fork Oil',
    'Handle Grip',
    'Hydrolic Switch',
    'Inner Tube',
    'Jettings',
    'Koso Evo 30mm',
    'Koso Evo 32mm',
    'LED Light',
    'Pito sa Gulong',
    'Pitsbike 34mm TB',
    'Pitsbike Crankshaft Bearing',
    'Pitsbike Oil Pump',
    'Pitsbike Racing ECU',
    'Pitsbike Tech 2 CDI',
    'Pitsbike TPS',
    'Race Power Monoshock4800',
    'Bom X Monoshock',
    'Bom  X Single Shifter',
    'Shims',
    'Sparkplug Brisk Blue',
    'Sparkplug Gpower',
    'Sparkplug Racing Red',
    'sgp oil strainer',
    'Stud Bolt',
    'Throttle Cable Shogun',
    'UMA Quick Throttle',
    'Velocity Throttle Body FI',
    'Voltmeter',
    'Yolac Cams',
    '8 Rows oil Cooler Carb with Installation',
    'RCB Front Caliper',
    'RCB Rear Caliper',
    'Bom X Handle Grip',
    'RCB/JRP Handle Grip',
    'Quantum Battery',
    'PCC SET',
    '180cc with 28mm Carb',
    '180cc FI',
    'Basic Set (ECU/TB/Dyno Tune)',
    'PortHicom',
    'REMAP w/ Wide Band Nut',
    'Superstock',
    'PMS 1',
    'PMS 2',
    'PMS 3',
    'TB cleaning',
    'Carb / Install',
    'Carb Cleaning',
    'Chain adjust',
    'Clearance/Shims',
    'Clutch Housing Repair',
    'Magneto Side Labor',
    'Full Wave',
    'Head Repair',
    'PIAA Package',
    'Reset Tensionare',
    'Valve Spring Seat'
));

DELETE FROM sale
WHERE id NOT IN (SELECT DISTINCT sale_id FROM sale_line);

DELETE FROM stock_in_line
WHERE product_id IN (SELECT id FROM product WHERE name NOT IN (
    'Balancer Dumper (2pcs)',
    'Spacer Mags Rear',
    'Spacer Mags Front',
    'Sprocket Set SSS Gold',
    'Sprocket Set SSS Gold Installation',
    'Sprocket Set SSS Silver',
    'Sprocket Set SSS Silver Installation',
    'Ignition Coil Protector (Carb)',
    'Ignition Coil Protector (FI)',
    'MDL Package - Basic',
    'MDL Package - Senlo T1/M1A 60W',
    'MDL Package - Senlo M5 100W',
    'Refresh (Carb)',
    'Refresh (FI)',
    'Clutch Side Labor (Carb)',
    'Clutch Side Labor (FI)',
    'Front Shock Tune',
    'Rear Shock Tune',
    'Rethread 6mm',
    'Rethread 7mm',
    'Rethread 8mm',
    'Mutarru Radiator (FI)',
    'Race Power Radiator (FI)',
    'Top Cover Bolt',
    'Balancer Gear Counter (Carb)',
    'Balancer Gear Counter (FI)',
    'Air Filter (Carb)',
    'Air Filter (FI)',
    'Balancer Crank',
    'Balancer Gear Carb/FI',
    'Balancer Inner Race',
    'Balancer Pin',
    'Balancer Spring',
    'Ball Race Carb/FI',
    'Base Gasket (Carb)',
    'Base Gasket (FI)',
    'Body Switch (Carb)',
    'Body Switch (FI)',
    'Break Pad Front (Carb)',
    'Break Pad Front (FI)',
    'Break Pad Rear (Carb)',
    'Break Pad Rear (FI)',
    'Chain Guide Long Carb/FI',
    'Chain Guide Short Carb/FI',
    'Clutch Arm',
    'Clutch Holder',
    'Clutch Cable (Carb)',
    'Clutch Cable (FI)',
    'Clutch Housing (Carb)',
    'Clutch Housing (FI)',
    'Clutch Hub (Carb)',
    'Clutch Hub (FI)',
    'Clutch Linning Carb/FI',
    'Clutch Plate',
    'Clutch Release Bearing',
    'Clutch Side Gasket Carb/FI',
    'Connecting Rod Kit Carb/FI',
    'Crankshaft Bearing Clutchside',
    'Crankshaft Bearing Magneto',
    'Drain Plug Bolts',
    'Dust Seal Front Shock',
    'Exhaust Cams Carb/FI',
    'Exhaust Valve (Carb)',
    'Exhaust Valve (FI)',
    'Fan Relay',
    'Front Shock Ring Stopper',
    'Fuel Filter (Carb)',
    'Fuel Filter (FI)',
    'Fuel Hose RFI',
    'Fuel Pump RFI',
    'Gasket Muffler',
    'Head Gasket FI',
    'High Tension Seal',
    'Idle Screw FI',
    'Ignition Switch Carb',
    'Ignition Switch FI',
    'Injector SGP',
    'Insulator Intake Pipe',
    'Intake Cams Carb/FI',
    'Intake Valve (Carb)',
    'Intake Valve (FI)',
    'Kunya Magneto',
    'Lens Oil Inspection',
    'Lever Break',
    'Lever Clutch',
    'Magento Gasket Carb/FI',
    'Manifold',
    'O Ring Insulator',
    'O Ring Neutral Sensor',
    'O Ring Oil Filter Cap',
    'O Ring Oil Filter Small',
    'Oil 1L',
    'Oil Cap',
    'Oil Filter',
    'Oil Filter Screen',
    'Oil Pump (Carb)',
    'Oil Pump (FI)',
    'Oil Pump Gear Carb/FI',
    'Oil Seal Clutch',
    'Oil Seal Driveshaft Carb/FI',
    'Oil Seal Front Shock',
    'Oil Seal Kambyo',
    'Oil Seal Kick',
    'Oil Seal Rear Shock',
    'Oil Seal Small',
    'Oil Seal Water Pump Case FI',
    'Pin Dowel Block',
    'Pin Dowel Block Head',
    'Piston  Carb/FI',
    'Piston Pin',
    'Piston Ring Carb/FI',
    'Pressure Plate (Carb)',
    'Pressure Plate (FI)',
    'Rack Release',
    'Return Spring',
    'Rotor Disk Front',
    'Rotor Disk Rear',
    'Rubber Dumper',
    'Shim Cap',
    'Side Mirror Reborn set',
    'Spacer Axle Front/Rear',
    'Spacer Bearing  Mags',
    'Sparkplug Cap Assy',
    'Sprocket Hub',
    'Sprocket Hub Spacer',
    'Starter Motor',
    'Starter Motor (Carb)',
    'Starter Motor (FI)',
    'Starter Relay',
    'Tensionare Carb/FI',
    'Tensioner Gasket',
    'Throttle Cable FI stock',
    'Timming Chain Carb/FI',
    'Top Cover Gasket',
    'Valve Lock',
    'Valve Retainer',
    'Valve Seal',
    'Valve Spring',
    'Vendix Drive Carb/FI',
    'Washer Block',
    'Washer Clutch Hub',
    'Water Pump Oil Seal',
    'Water Pump Shaft',
    'Water Temperature Sensor',
    'Wave Washer (Carb)',
    'Wave Washer (FI)',
    'Bearing 6002',
    'Bearing 6004',
    'Bearing 6200',
    'Bearing 6201',
    'Bearing 6202',
    'Bearing 6203',
    'Bearing 6204',
    'Bearing 6301',
    'Aircut',
    'Block 62mm steel Carb/FI',
    'Block 62mm Steel FI',
    'Block 68mm Chrome Bore FI',
    'Block 68mm Steel Carb',
    'Break Hose Front',
    'Break Hose Rear',
    'Breather Filter set FI',
    'Carbon Brush (Carb)',
    'Carbon Brush (FI)',
    'Carburetor Cleaner',
    'Clutch Spring set',
    'Coolant',
    'Domino Switch',
    'Elbow (Carb)',
    'Elbow (FI)',
    'Exos Pipe Set (Carb)',
    'Exos Pipe Set (FI)',
    'Exhaust Gasket',
    'Faito Connecting Rod Kit with Bearing',
    'Fork Oil',
    'Handle Grip',
    'Hydrolic Switch',
    'Inner Tube',
    'Jettings',
    'Koso Evo 30mm',
    'Koso Evo 32mm',
    'LED Light',
    'Pito sa Gulong',
    'Pitsbike 34mm TB',
    'Pitsbike Crankshaft Bearing',
    'Pitsbike Oil Pump',
    'Pitsbike Racing ECU',
    'Pitsbike Tech 2 CDI',
    'Pitsbike TPS',
    'Race Power Monoshock4800',
    'Bom X Monoshock',
    'Bom  X Single Shifter',
    'Shims',
    'Sparkplug Brisk Blue',
    'Sparkplug Gpower',
    'Sparkplug Racing Red',
    'sgp oil strainer',
    'Stud Bolt',
    'Throttle Cable Shogun',
    'UMA Quick Throttle',
    'Velocity Throttle Body FI',
    'Voltmeter',
    'Yolac Cams',
    '8 Rows oil Cooler Carb with Installation',
    'RCB Front Caliper',
    'RCB Rear Caliper',
    'Bom X Handle Grip',
    'RCB/JRP Handle Grip',
    'Quantum Battery',
    'PCC SET',
    '180cc with 28mm Carb',
    '180cc FI',
    'Basic Set (ECU/TB/Dyno Tune)',
    'PortHicom',
    'REMAP w/ Wide Band Nut',
    'Superstock',
    'PMS 1',
    'PMS 2',
    'PMS 3',
    'TB cleaning',
    'Carb / Install',
    'Carb Cleaning',
    'Chain adjust',
    'Clearance/Shims',
    'Clutch Housing Repair',
    'Magneto Side Labor',
    'Full Wave',
    'Head Repair',
    'PIAA Package',
    'Reset Tensionare',
    'Valve Spring Seat'
));

DELETE FROM stock_in
WHERE id NOT IN (SELECT DISTINCT stock_in_id FROM stock_in_line);

DELETE FROM stock_level
WHERE product_id IN (SELECT id FROM product WHERE name NOT IN (
    'Balancer Dumper (2pcs)',
    'Spacer Mags Rear',
    'Spacer Mags Front',
    'Sprocket Set SSS Gold',
    'Sprocket Set SSS Gold Installation',
    'Sprocket Set SSS Silver',
    'Sprocket Set SSS Silver Installation',
    'Ignition Coil Protector (Carb)',
    'Ignition Coil Protector (FI)',
    'MDL Package - Basic',
    'MDL Package - Senlo T1/M1A 60W',
    'MDL Package - Senlo M5 100W',
    'Refresh (Carb)',
    'Refresh (FI)',
    'Clutch Side Labor (Carb)',
    'Clutch Side Labor (FI)',
    'Front Shock Tune',
    'Rear Shock Tune',
    'Rethread 6mm',
    'Rethread 7mm',
    'Rethread 8mm',
    'Mutarru Radiator (FI)',
    'Race Power Radiator (FI)',
    'Top Cover Bolt',
    'Balancer Gear Counter (Carb)',
    'Balancer Gear Counter (FI)',
    'Air Filter (Carb)',
    'Air Filter (FI)',
    'Balancer Crank',
    'Balancer Gear Carb/FI',
    'Balancer Inner Race',
    'Balancer Pin',
    'Balancer Spring',
    'Ball Race Carb/FI',
    'Base Gasket (Carb)',
    'Base Gasket (FI)',
    'Body Switch (Carb)',
    'Body Switch (FI)',
    'Break Pad Front (Carb)',
    'Break Pad Front (FI)',
    'Break Pad Rear (Carb)',
    'Break Pad Rear (FI)',
    'Chain Guide Long Carb/FI',
    'Chain Guide Short Carb/FI',
    'Clutch Arm',
    'Clutch Holder',
    'Clutch Cable (Carb)',
    'Clutch Cable (FI)',
    'Clutch Housing (Carb)',
    'Clutch Housing (FI)',
    'Clutch Hub (Carb)',
    'Clutch Hub (FI)',
    'Clutch Linning Carb/FI',
    'Clutch Plate',
    'Clutch Release Bearing',
    'Clutch Side Gasket Carb/FI',
    'Connecting Rod Kit Carb/FI',
    'Crankshaft Bearing Clutchside',
    'Crankshaft Bearing Magneto',
    'Drain Plug Bolts',
    'Dust Seal Front Shock',
    'Exhaust Cams Carb/FI',
    'Exhaust Valve (Carb)',
    'Exhaust Valve (FI)',
    'Fan Relay',
    'Front Shock Ring Stopper',
    'Fuel Filter (Carb)',
    'Fuel Filter (FI)',
    'Fuel Hose RFI',
    'Fuel Pump RFI',
    'Gasket Muffler',
    'Head Gasket FI',
    'High Tension Seal',
    'Idle Screw FI',
    'Ignition Switch Carb',
    'Ignition Switch FI',
    'Injector SGP',
    'Insulator Intake Pipe',
    'Intake Cams Carb/FI',
    'Intake Valve (Carb)',
    'Intake Valve (FI)',
    'Kunya Magneto',
    'Lens Oil Inspection',
    'Lever Break',
    'Lever Clutch',
    'Magento Gasket Carb/FI',
    'Manifold',
    'O Ring Insulator',
    'O Ring Neutral Sensor',
    'O Ring Oil Filter Cap',
    'O Ring Oil Filter Small',
    'Oil 1L',
    'Oil Cap',
    'Oil Filter',
    'Oil Filter Screen',
    'Oil Pump (Carb)',
    'Oil Pump (FI)',
    'Oil Pump Gear Carb/FI',
    'Oil Seal Clutch',
    'Oil Seal Driveshaft Carb/FI',
    'Oil Seal Front Shock',
    'Oil Seal Kambyo',
    'Oil Seal Kick',
    'Oil Seal Rear Shock',
    'Oil Seal Small',
    'Oil Seal Water Pump Case FI',
    'Pin Dowel Block',
    'Pin Dowel Block Head',
    'Piston  Carb/FI',
    'Piston Pin',
    'Piston Ring Carb/FI',
    'Pressure Plate (Carb)',
    'Pressure Plate (FI)',
    'Rack Release',
    'Return Spring',
    'Rotor Disk Front',
    'Rotor Disk Rear',
    'Rubber Dumper',
    'Shim Cap',
    'Side Mirror Reborn set',
    'Spacer Axle Front/Rear',
    'Spacer Bearing  Mags',
    'Sparkplug Cap Assy',
    'Sprocket Hub',
    'Sprocket Hub Spacer',
    'Starter Motor',
    'Starter Motor (Carb)',
    'Starter Motor (FI)',
    'Starter Relay',
    'Tensionare Carb/FI',
    'Tensioner Gasket',
    'Throttle Cable FI stock',
    'Timming Chain Carb/FI',
    'Top Cover Gasket',
    'Valve Lock',
    'Valve Retainer',
    'Valve Seal',
    'Valve Spring',
    'Vendix Drive Carb/FI',
    'Washer Block',
    'Washer Clutch Hub',
    'Water Pump Oil Seal',
    'Water Pump Shaft',
    'Water Temperature Sensor',
    'Wave Washer (Carb)',
    'Wave Washer (FI)',
    'Bearing 6002',
    'Bearing 6004',
    'Bearing 6200',
    'Bearing 6201',
    'Bearing 6202',
    'Bearing 6203',
    'Bearing 6204',
    'Bearing 6301',
    'Aircut',
    'Block 62mm steel Carb/FI',
    'Block 62mm Steel FI',
    'Block 68mm Chrome Bore FI',
    'Block 68mm Steel Carb',
    'Break Hose Front',
    'Break Hose Rear',
    'Breather Filter set FI',
    'Carbon Brush (Carb)',
    'Carbon Brush (FI)',
    'Carburetor Cleaner',
    'Clutch Spring set',
    'Coolant',
    'Domino Switch',
    'Elbow (Carb)',
    'Elbow (FI)',
    'Exos Pipe Set (Carb)',
    'Exos Pipe Set (FI)',
    'Exhaust Gasket',
    'Faito Connecting Rod Kit with Bearing',
    'Fork Oil',
    'Handle Grip',
    'Hydrolic Switch',
    'Inner Tube',
    'Jettings',
    'Koso Evo 30mm',
    'Koso Evo 32mm',
    'LED Light',
    'Pito sa Gulong',
    'Pitsbike 34mm TB',
    'Pitsbike Crankshaft Bearing',
    'Pitsbike Oil Pump',
    'Pitsbike Racing ECU',
    'Pitsbike Tech 2 CDI',
    'Pitsbike TPS',
    'Race Power Monoshock4800',
    'Bom X Monoshock',
    'Bom  X Single Shifter',
    'Shims',
    'Sparkplug Brisk Blue',
    'Sparkplug Gpower',
    'Sparkplug Racing Red',
    'sgp oil strainer',
    'Stud Bolt',
    'Throttle Cable Shogun',
    'UMA Quick Throttle',
    'Velocity Throttle Body FI',
    'Voltmeter',
    'Yolac Cams',
    '8 Rows oil Cooler Carb with Installation',
    'RCB Front Caliper',
    'RCB Rear Caliper',
    'Bom X Handle Grip',
    'RCB/JRP Handle Grip',
    'Quantum Battery',
    'PCC SET',
    '180cc with 28mm Carb',
    '180cc FI',
    'Basic Set (ECU/TB/Dyno Tune)',
    'PortHicom',
    'REMAP w/ Wide Band Nut',
    'Superstock',
    'PMS 1',
    'PMS 2',
    'PMS 3',
    'TB cleaning',
    'Carb / Install',
    'Carb Cleaning',
    'Chain adjust',
    'Clearance/Shims',
    'Clutch Housing Repair',
    'Magneto Side Labor',
    'Full Wave',
    'Head Repair',
    'PIAA Package',
    'Reset Tensionare',
    'Valve Spring Seat'
));

DELETE FROM product
WHERE name NOT IN (
    'Balancer Dumper (2pcs)',
    'Spacer Mags Rear',
    'Spacer Mags Front',
    'Sprocket Set SSS Gold',
    'Sprocket Set SSS Gold Installation',
    'Sprocket Set SSS Silver',
    'Sprocket Set SSS Silver Installation',
    'Ignition Coil Protector (Carb)',
    'Ignition Coil Protector (FI)',
    'MDL Package - Basic',
    'MDL Package - Senlo T1/M1A 60W',
    'MDL Package - Senlo M5 100W',
    'Refresh (Carb)',
    'Refresh (FI)',
    'Clutch Side Labor (Carb)',
    'Clutch Side Labor (FI)',
    'Front Shock Tune',
    'Rear Shock Tune',
    'Rethread 6mm',
    'Rethread 7mm',
    'Rethread 8mm',
    'Mutarru Radiator (FI)',
    'Race Power Radiator (FI)',
    'Top Cover Bolt',
    'Balancer Gear Counter (Carb)',
    'Balancer Gear Counter (FI)',
    'Air Filter (Carb)',
    'Air Filter (FI)',
    'Balancer Crank',
    'Balancer Gear Carb/FI',
    'Balancer Inner Race',
    'Balancer Pin',
    'Balancer Spring',
    'Ball Race Carb/FI',
    'Base Gasket (Carb)',
    'Base Gasket (FI)',
    'Body Switch (Carb)',
    'Body Switch (FI)',
    'Break Pad Front (Carb)',
    'Break Pad Front (FI)',
    'Break Pad Rear (Carb)',
    'Break Pad Rear (FI)',
    'Chain Guide Long Carb/FI',
    'Chain Guide Short Carb/FI',
    'Clutch Arm',
    'Clutch Holder',
    'Clutch Cable (Carb)',
    'Clutch Cable (FI)',
    'Clutch Housing (Carb)',
    'Clutch Housing (FI)',
    'Clutch Hub (Carb)',
    'Clutch Hub (FI)',
    'Clutch Linning Carb/FI',
    'Clutch Plate',
    'Clutch Release Bearing',
    'Clutch Side Gasket Carb/FI',
    'Connecting Rod Kit Carb/FI',
    'Crankshaft Bearing Clutchside',
    'Crankshaft Bearing Magneto',
    'Drain Plug Bolts',
    'Dust Seal Front Shock',
    'Exhaust Cams Carb/FI',
    'Exhaust Valve (Carb)',
    'Exhaust Valve (FI)',
    'Fan Relay',
    'Front Shock Ring Stopper',
    'Fuel Filter (Carb)',
    'Fuel Filter (FI)',
    'Fuel Hose RFI',
    'Fuel Pump RFI',
    'Gasket Muffler',
    'Head Gasket FI',
    'High Tension Seal',
    'Idle Screw FI',
    'Ignition Switch Carb',
    'Ignition Switch FI',
    'Injector SGP',
    'Insulator Intake Pipe',
    'Intake Cams Carb/FI',
    'Intake Valve (Carb)',
    'Intake Valve (FI)',
    'Kunya Magneto',
    'Lens Oil Inspection',
    'Lever Break',
    'Lever Clutch',
    'Magento Gasket Carb/FI',
    'Manifold',
    'O Ring Insulator',
    'O Ring Neutral Sensor',
    'O Ring Oil Filter Cap',
    'O Ring Oil Filter Small',
    'Oil 1L',
    'Oil Cap',
    'Oil Filter',
    'Oil Filter Screen',
    'Oil Pump (Carb)',
    'Oil Pump (FI)',
    'Oil Pump Gear Carb/FI',
    'Oil Seal Clutch',
    'Oil Seal Driveshaft Carb/FI',
    'Oil Seal Front Shock',
    'Oil Seal Kambyo',
    'Oil Seal Kick',
    'Oil Seal Rear Shock',
    'Oil Seal Small',
    'Oil Seal Water Pump Case FI',
    'Pin Dowel Block',
    'Pin Dowel Block Head',
    'Piston  Carb/FI',
    'Piston Pin',
    'Piston Ring Carb/FI',
    'Pressure Plate (Carb)',
    'Pressure Plate (FI)',
    'Rack Release',
    'Return Spring',
    'Rotor Disk Front',
    'Rotor Disk Rear',
    'Rubber Dumper',
    'Shim Cap',
    'Side Mirror Reborn set',
    'Spacer Axle Front/Rear',
    'Spacer Bearing  Mags',
    'Sparkplug Cap Assy',
    'Sprocket Hub',
    'Sprocket Hub Spacer',
    'Starter Motor',
    'Starter Motor (Carb)',
    'Starter Motor (FI)',
    'Starter Relay',
    'Tensionare Carb/FI',
    'Tensioner Gasket',
    'Throttle Cable FI stock',
    'Timming Chain Carb/FI',
    'Top Cover Gasket',
    'Valve Lock',
    'Valve Retainer',
    'Valve Seal',
    'Valve Spring',
    'Vendix Drive Carb/FI',
    'Washer Block',
    'Washer Clutch Hub',
    'Water Pump Oil Seal',
    'Water Pump Shaft',
    'Water Temperature Sensor',
    'Wave Washer (Carb)',
    'Wave Washer (FI)',
    'Bearing 6002',
    'Bearing 6004',
    'Bearing 6200',
    'Bearing 6201',
    'Bearing 6202',
    'Bearing 6203',
    'Bearing 6204',
    'Bearing 6301',
    'Aircut',
    'Block 62mm steel Carb/FI',
    'Block 62mm Steel FI',
    'Block 68mm Chrome Bore FI',
    'Block 68mm Steel Carb',
    'Break Hose Front',
    'Break Hose Rear',
    'Breather Filter set FI',
    'Carbon Brush (Carb)',
    'Carbon Brush (FI)',
    'Carburetor Cleaner',
    'Clutch Spring set',
    'Coolant',
    'Domino Switch',
    'Elbow (Carb)',
    'Elbow (FI)',
    'Exos Pipe Set (Carb)',
    'Exos Pipe Set (FI)',
    'Exhaust Gasket',
    'Faito Connecting Rod Kit with Bearing',
    'Fork Oil',
    'Handle Grip',
    'Hydrolic Switch',
    'Inner Tube',
    'Jettings',
    'Koso Evo 30mm',
    'Koso Evo 32mm',
    'LED Light',
    'Pito sa Gulong',
    'Pitsbike 34mm TB',
    'Pitsbike Crankshaft Bearing',
    'Pitsbike Oil Pump',
    'Pitsbike Racing ECU',
    'Pitsbike Tech 2 CDI',
    'Pitsbike TPS',
    'Race Power Monoshock4800',
    'Bom X Monoshock',
    'Bom  X Single Shifter',
    'Shims',
    'Sparkplug Brisk Blue',
    'Sparkplug Gpower',
    'Sparkplug Racing Red',
    'sgp oil strainer',
    'Stud Bolt',
    'Throttle Cable Shogun',
    'UMA Quick Throttle',
    'Velocity Throttle Body FI',
    'Voltmeter',
    'Yolac Cams',
    '8 Rows oil Cooler Carb with Installation',
    'RCB Front Caliper',
    'RCB Rear Caliper',
    'Bom X Handle Grip',
    'RCB/JRP Handle Grip',
    'Quantum Battery',
    'PCC SET',
    '180cc with 28mm Carb',
    '180cc FI',
    'Basic Set (ECU/TB/Dyno Tune)',
    'PortHicom',
    'REMAP w/ Wide Band Nut',
    'Superstock',
    'PMS 1',
    'PMS 2',
    'PMS 3',
    'TB cleaning',
    'Carb / Install',
    'Carb Cleaning',
    'Chain adjust',
    'Clearance/Shims',
    'Clutch Housing Repair',
    'Magneto Side Labor',
    'Full Wave',
    'Head Repair',
    'PIAA Package',
    'Reset Tensionare',
    'Valve Spring Seat'
);
